# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Login

POST https://localhost:7202/api/Auth/Login
Content-Type: application/json

{
  "email": "hernan3@example.com",
  "password": "@Password123"
}

### Obtener mi sesión
GET https://localhost:7202/api/Auth/Session
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImRhYTRmYTNhLWQzMDktNDNiYy1iNGUwLWU0YWJiN2YyZjJmMSIsImp0aSI6ImMwZDJlOWYzLTRjMjgtNDAxOC04ZTQ1LTQxMGI4N2E1Yzc0ZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzIwMDg4Mjk4LCJpc3MiOiJtYW50ZW5pbWllbnRvc2ltcGxlLmFwaSJ9.NoaM9ymzNNTeKdMhDwnkjAdIO9uYeHrtnJSo2YsBB1E


### Obtener todos los usuarios

GET https://localhost:7202/api/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImRhYTRmYTNhLWQzMDktNDNiYy1iNGUwLWU0YWJiN2YyZjJmMSIsImp0aSI6ImMwZDJlOWYzLTRjMjgtNDAxOC04ZTQ1LTQxMGI4N2E1Yzc0ZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzIwMDg4Mjk4LCJpc3MiOiJtYW50ZW5pbWllbnRvc2ltcGxlLmFwaSJ9.NoaM9ymzNNTeKdMhDwnkjAdIO9uYeHrtnJSo2YsBB1E

### Crear usuario

POST https://localhost:7202/api/Users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImRhYTRmYTNhLWQzMDktNDNiYy1iNGUwLWU0YWJiN2YyZjJmMSIsImp0aSI6ImMwZDJlOWYzLTRjMjgtNDAxOC04ZTQ1LTQxMGI4N2E1Yzc0ZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzIwMDg4Mjk4LCJpc3MiOiJtYW50ZW5pbWllbnRvc2ltcGxlLmFwaSJ9.NoaM9ymzNNTeKdMhDwnkjAdIO9uYeHrtnJSo2YsBB1E

{
  "username": "acerohernan5",
  "email": "hernan5@example.com",
  "password": "@Password123",
  "confirmPassword": "@Password123",
  "role": "Editor"
}

### Editar usuario
@id = 34b536f4-8165-49fc-916a-88b9972461fc

PATCH https://localhost:7202/api/Users/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImRhYTRmYTNhLWQzMDktNDNiYy1iNGUwLWU0YWJiN2YyZjJmMSIsImp0aSI6ImMwZDJlOWYzLTRjMjgtNDAxOC04ZTQ1LTQxMGI4N2E1Yzc0ZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzIwMDg4Mjk4LCJpc3MiOiJtYW50ZW5pbWllbnRvc2ltcGxlLmFwaSJ9.NoaM9ymzNNTeKdMhDwnkjAdIO9uYeHrtnJSo2YsBB1E

{
  "username": "acerohernansadsa",
  "email": "hernanssa@example.com",
  "rol": "Editor"
} 

### 
@id = 34b536f4-8165-49fc-916a-88b9972461fc

DELETE https://localhost:7202/api/Users/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImRhYTRmYTNhLWQzMDktNDNiYy1iNGUwLWU0YWJiN2YyZjJmMSIsImp0aSI6ImMwZDJlOWYzLTRjMjgtNDAxOC04ZTQ1LTQxMGI4N2E1Yzc0ZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzIwMDg4Mjk4LCJpc3MiOiJtYW50ZW5pbWllbnRvc2ltcGxlLmFwaSJ9.NoaM9ymzNNTeKdMhDwnkjAdIO9uYeHrtnJSo2YsBB1E